// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByTtoSn2uiJcfCaM8cmcgbhcuR5RczwmE',
    appId: '1:157500127370:android:58e895c5a8b652ca925573',
    messagingSenderId: '157500127370',
    projectId: 'testing-5305a',
    databaseURL: 'https://testing-5305a-default-rtdb.firebaseio.com',
    storageBucket: 'testing-5305a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr1iSQYKKhF6JXSFwzX1J-mPZmqbtyL8s',
    appId: '1:157500127370:ios:e75b1d40233dfa35925573',
    messagingSenderId: '157500127370',
    projectId: 'testing-5305a',
    databaseURL: 'https://testing-5305a-default-rtdb.firebaseio.com',
    storageBucket: 'testing-5305a.appspot.com',
    iosClientId: '157500127370-dv6t5kksml1dmv8uq9jitiashbtdiene.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp',
  );
}
